<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 45" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="C:\Users\s528358\workspace\LovePython\Sort_test.py" status="error" test="Sort_test" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\s528358\.p2\pool\plugins\org.python.pydev_5.5.0.201701191708\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:\Users\s528358\workspace\LovePython\Sort_test.py", line 26, in <module>
    t.test_InsertionSort()
TypeError: test_InsertionSort() missing 1 required positional argument: 'self'
ERROR: Module: Sort_test could not be imported (file: C:\Users\s528358\workspace\LovePython\Sort_test.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="LovePython Sort_test.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
