<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 4" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="C:\Users\s528358\workspace\LovePython\Susan_Test_Practise.py" status="error" test="Susan_Test_Practise" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\s528358\.p2\pool\plugins\org.python.pydev_5.3.1.201610311318\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:\Users\s528358\workspace\LovePython\Susan_Test_Practise.py", line 7, in <module>
    for i in var:
io.UnsupportedOperation: not readable
ERROR: Module: Susan_Test_Practise could not be imported (file: C:\Users\s528358\workspace\LovePython\Susan_Test_Practise.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="LovePython Susan_Test_Practise.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
